PKGCONFIG_BIN=/usr/bin/pkg-config
PKGCONFIG_BIN_BREW=/home/linuxbrew/.linuxbrew/bin/pkg-config

## compiler flags

COMMON_DEFINES := \
-DBOOST_LOG_DYN_LINK \
-DBIGARRAY_MULTIPLIER=1 \
-DUSING_XED \
-DUSE_CUSTOM_TAG \
-DTARGET_IA32E \
-DHOST_IA32E \
-DTARGET_LINUX
SIZE8_FLAGS := \
-DLIBDFT_TAG_TYPE=theia_tag_set_u8 \
-DUNIT_TAG_TYPE=theia_tag_u8
SIZE16_FLAGS := $(SIZE8_FLAGS:u8=u16)
SIZE32_FLAGS := $(SIZE8_FLAGS:u8=u32)
SIZE64_FLAGS := $(SIZE8_FLAGS:u8=u64)
#REPLAY :=
REPLAY := -DTHEIA_REPLAY_COMPENSATION
COMMON_FLAGS := \
-Wall \
-Werror \
-Wno-unknown-pragmas \
-Wno-deprecated-declarations \
-Wno-unused-local-typedefs \
-O0 \
-std=c++0x \
-g \
-fno-stack-protector \
-fPIC \
-fomit-frame-pointer \
-fno-strict-aliasing \
-static-libgcc \
-static-libstdc++

PIN_STUFF := /usr/local/taint/include/pin
PIN_INCLUDES := -I$(PIN_STUFF)
GLIB_INCLUDES := $(shell $(PKGCONFIG_BIN) --cflags glib-2.0)
#BOOST_INCLUDES := -I/home/linuxbrew/.linuxbrew/opt/boost/include
BOOST_INCLUDES :=
TCTA3CPP_INCLUDES := -I/usr/local/taint/include/libtcta3cpp 
PQXX_INCLUDES := $(shell $(PKGCONFIG_BIN) --cflags libpqxx)
RDKAFKA_INCLUDES := $(shell $(PKGCONFIG_BIN) --cflags rdkafka++)

#FIX_BREW := -Wl,-dynamic-linker=/lib64/ld-linux-x86-64.so.2 -Wl,-rpath=/usr/local/lib
#EXTRA_LDFLAGS := -static-libgcc -static-libstdc++
#FIX_BREW := $(EXTRA_LDFLAGS) -B/home/linuxbrew/.linuxbrew/opt/gcc/libexec/gcc/x86_64-unknown-linux-gnu/5.5.0/
FIX_BREW :=

COMMON_CXXFLAGS := \
$(COMMON_DEFINES) \
$(REPLAY) \
$(COMMON_FLAGS) \
$(FIX_BREW) \
-I/usr/local/taint/include \
$(PIN_INCLUDES) \
$(GLIB_INCLUDES) \
$(BOOST_INCLUDES) \
$(TCTA3CPP_INCLUDES) \
$(PQXX_INCLUDES) \
$(RDKAFKA_INCLUDES) \
-I../../src

## linker flags

#test for boost multithread build
MT := $(shell { g++ -lboost_thread 2>&1 | grep -q 'cannot find -lboost_thread' && echo '-mt'; })

PIN_LIBADD := -lpin -lxed -ldwarf -lelf -ldl
PQXX_LIBADD := -lpqxx
TCTA3CPP_LIBADD := -ltcta3cpp -lavrocpp
GLIB_LIBADD := -lglib-2.0
RDKAFKA_LIBADD := -lrdkafka++
BOOST_LIBADD := \
-lboost_log$(MT) \
-lboost_program_options$(MT) \
-lboost_log_setup$(MT) \
-lboost_thread$(MT) \
-lboost_system$(MT) \
-lboost_serialization$(MT) \
-lboost_filesystem$(MT) \
-lpthread 

COMMON_LIBADD := \
$(PIN_LIBADD) \
$(PQXX_LIBADD) \
$(TCTA3CPP_LIBADD) \
$(GLIB_LIBADD) \
$(RDKAFKA_LIBADD) \
$(BOOST_LIBADD)

TOOLS_LDFLAGS := -Wl,--hash-style=sysv -Wl,-Bsymbolic -Wl,--version-script=$(PIN_STUFF)/pintool.ver
COMMON_LDFLAGS := $(FIX_BREW) $(TOOLS_LDFLAGS) -L/usr/local/taint/lib -L$(builddir)/../src
