## misc stuff
taint_prefix:=/usr/local/taint
taint_libs:=$(taint_prefix)/lib
taint_pkgconfig:=$(taint_libs)/pkgconfig
taint_includes:=$(taint_prefix)/include

#add taint_pkgconfig to env if needed
ifeq ($(findstring $(taint_pkgconfig), $(PKG_CONFIG_PATH)),)
    PKG_CONFIG_PATH:=$(taint_pkgconfig):$(PKG_CONFIG_PATH)
endif

PKGCONFIG_BIN:=$(shell which /usr/bin/pkg-config)
#PKGCONFIG_BIN=/home/linuxbrew/.linuxbrew/bin/pkg-config
ifeq ($(strip $(PKGCONFIG_BIN)),)
    $(error missing pkg-config. fix with: apt-get install pkg-config)
endif

## compiler flags

#hack for compiling libdft_dta64 four different times with a different tag size
ifndef TAG_SIZE
   	$(error TAG_SIZE must be set to 8, 16, 32, or 64)
else ifeq ($(strip $(TAG_SIZE)),) #empty
    $(error TAG_SIZE must be set to 8, 16, 32, or 64)
else ifeq ($(strip $(TAG_SIZE)), 8)
    TAG_SIZE_FLAGS := \
					  -DLIBDFT_TAG_TYPE=theia_tag_set_u8 \
					  -DUNIT_TAG_TYPE=theia_tag_u8
else ifeq ($(strip $(TAG_SIZE)), 16)
    TAG_SIZE_FLAGS := \
					  -DLIBDFT_TAG_TYPE=theia_tag_set_u16 \
					  -DUNIT_TAG_TYPE=theia_tag_u16
else ifeq ($(strip $(TAG_SIZE)), 32)
    TAG_SIZE_FLAGS := \
					  -DLIBDFT_TAG_TYPE=theia_tag_set_u32 \
					  -DUNIT_TAG_TYPE=theia_tag_u32
else ifeq ($(strip $(TAG_SIZE)), 64)
    TAG_SIZE_FLAGS := \
					  -DLIBDFT_TAG_TYPE=theia_tag_set_u64 \
					  -DUNIT_TAG_TYPE=theia_tag_u64
endif
COMMON_DEFINES := \
-DBOOST_LOG_DYN_LINK \
-DBIGARRAY_MULTIPLIER=1 \
-DUSING_XED \
-DUSE_CUSTOM_TAG \
-DTARGET_IA32E \
-DHOST_IA32E \
-DTARGET_LINUX
#REPLAY :=
REPLAY := -DTHEIA_REPLAY_COMPENSATION
COMMON_FLAGS := \
-Wall \
-Werror \
-Wno-unknown-pragmas \
-Wno-deprecated-declarations \
-Wno-unused-local-typedefs \
-O0 \
-std=c++0x \
-g \
-fno-stack-protector \
-fPIC \
-fomit-frame-pointer \
-fno-strict-aliasing \


GLIB_INCLUDES := $(shell $(PKGCONFIG_BIN) --cflags glib-2.0)
PQXX_INCLUDES := $(shell $(PKGCONFIG_BIN) --cflags libpqxx)
RDKAFKA_INCLUDES := $(shell $(PKGCONFIG_BIN) --cflags rdkafka++)
#PIN_STUFF is PIN_INCLUDES without -I
PIN_STUFF := $(taint_includes)/pin
PIN_INCLUDES := -I$(PIN_STUFF)
#BOOST_INCLUDES := -I/home/linuxbrew/.linuxbrew/opt/boost/include
BOOST_INCLUDES :=
TCTA3CPP_INCLUDES := -I$(taint_includes)/libtcta3cpp

#FIX_BREW := -Wl,-dynamic-linker=/lib64/ld-linux-x86-64.so.2 -Wl,-rpath=/usr/local/lib
#EXTRA_LDFLAGS := -static-libgcc -static-libstdc++
#FIX_BREW := $(EXTRA_LDFLAGS) -B/home/linuxbrew/.linuxbrew/opt/gcc/libexec/gcc/x86_64-unknown-linux-gnu/5.5.0/
FIX_BREW :=

COMMON_CXXFLAGS := \
$(COMMON_DEFINES) \
$(TAG_SIZE_FLAGS) \
$(REPLAY) \
$(COMMON_FLAGS) \
$(FIX_BREW) \
-I$(taint_includes) \
$(PIN_INCLUDES) \
$(GLIB_INCLUDES) \
$(BOOST_INCLUDES) \
$(TCTA3CPP_INCLUDES) \
$(PQXX_INCLUDES) \
$(RDKAFKA_INCLUDES) \
-I$(abs_top_srcdir)/src

## linker flags

#test for boost multithread build
MT := $(shell { g++ -lboost_thread 2>&1 | grep -q 'cannot find -lboost_thread' && echo '-mt'; })

PQXX_LIBADD := $(shell $(PKGCONFIG_BIN) --libs libpqxx)
GLIB_LIBADD := $(shell $(PKGCONFIG_BIN) --libs glib-2.0)
RDKAFKA_LIBADD := $(shell $(PKGCONFIG_BIN) --libs rdkafka++)
PIN_LIBADD := -lpin -lxed -ldwarf -lelf -ldl
TCTA3CPP_LIBADD := -ltcta3cpp -lavrocpp
BOOST_LIBADD := \
-lboost_log$(MT) \
-lboost_program_options$(MT) \
-lboost_log_setup$(MT) \
-lboost_thread$(MT) \
-lboost_system$(MT) \
-lboost_serialization$(MT) \
-lboost_filesystem$(MT) \
-lpthread

COMMON_LIBADD := \
$(PIN_LIBADD) \
$(PQXX_LIBADD) \
$(TCTA3CPP_LIBADD) \
$(GLIB_LIBADD) \
$(RDKAFKA_LIBADD) \
$(BOOST_LIBADD)

TOOLS_LDFLAGS := -Wl,--hash-style=sysv -Wl,-Bsymbolic -Wl,--version-script=$(PIN_STUFF)/pintool.ver
COMMON_LDFLAGS := $(FIX_BREW) $(TOOLS_LDFLAGS) -L$(taint_libs) -L$(builddir)/../src
